<?php
/**
 * EtimClassTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ETIM API
 *
 * ETIM International webservices.       - [Extra documentation and testclient](https://bitbucket.org/3xt/etimapi-rest-client/src/master/)
 *
 * OpenAPI spec version: 2.0
 * Contact: info@etim-international.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EtimClassTest Class Doc Comment
 *
 * @category    Class
 * @description EtimClass
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EtimClassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EtimClass"
     */
    public function testEtimClass()
    {
    }

    /**
     * Test attribute "parms"
     */
    public function testPropertyParms()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "mutation_date"
     */
    public function testPropertyMutationDate()
    {
    }

    /**
     * Test attribute "modelling"
     */
    public function testPropertyModelling()
    {
    }

    /**
     * Test attribute "dimensional_drawing_svg_url"
     */
    public function testPropertyDimensionalDrawingSvgUrl()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "synonyms"
     */
    public function testPropertySynonyms()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "features"
     */
    public function testPropertyFeatures()
    {
    }

    /**
     * Test attribute "linked_modelling_classes"
     */
    public function testPropertyLinkedModellingClasses()
    {
    }

    /**
     * Test attribute "linked_regular_classes"
     */
    public function testPropertyLinkedRegularClasses()
    {
    }

    /**
     * Test attribute "releases"
     */
    public function testPropertyReleases()
    {
    }

    /**
     * Test attribute "translations"
     */
    public function testPropertyTranslations()
    {
    }

    /**
     * Test attribute "change_code"
     */
    public function testPropertyChangeCode()
    {
    }
}
